modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
Additional modules for Draconic Evolution
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="draconicevolution"
mandatory=true
versionRange="[${de_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="brandonscore"
mandatory=true
versionRange="[${bcore_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=false
versionRange="[${curios_version},)"
ordering="AFTER"
side="BOTH"
